# paths
HE_OMETIF_FILEPATH="/path"
CYCIF_OMETIF_FILEPATH="/path"
CYCIF_MARKER_FILEPATH="/path"
PYRAMID_FILEPATH="/path"
WORK_DIRPATH="/path"
CODE_DIRPATH="/path"

# critical params
CYCIF_AF_CHANNELS="[DNA1,bg2a,bg3a,bg4a]"
AFFINE_NRES=8
AFFINE_NITER=10000

# less critical params
CHUNKSIZE="[1000,1000]"
FINAL_DTYPE="uint16"
RGB=(r g b)
PYRAMID_TILE_SIZE=1024

# intermediate file paths
CYCIF_H5_FILEPATH="$WORK_DIRPATH/cycif.h5"
HE_RGB_H5_FILEPATH="$WORK_DIRPATH/he_rgb.h5"
HE_GRAY_H5_FILEPATH="$WORK_DIRPATH/he_gray.h5"
CYCIF_TIFF_FILEPATH="$WORK_DIRPATH/cycif.tif"
HE_TIFF_FILEPATH="$WORK_DIRPATH/he.tif"
VIZ_REG_FILEPATH="$WORK_DIRPATH/viz_reg.tif"
TMP_TIFF_FILEPATH="$WORK_DIRPATH/tmp.tif"
TMP_FILELIST_FILEPATH="$WORK_DIRPATH/tmp_filelist.txt"
PARAM_FILEPATH="$WORK_DIRPATH/TransformParameters.0.txt"
FILELIST_FILEPATH="$WORK_DIRPATH/filelist.txt"
